extern   proc_nwln, proc_PutStr
extern   proc_GetStr, proc_GetCh
extern   proc_PutInt, proc_GetInt
extern   proc_PutLInt, proc_GetLInt

STDIN  equ 0
STDOUT equ 1
STDERR equ 2
 
SYS_READ  equ 3
SYS_WRITE equ 4
SYS_EXIT  equ 1

;;-------------------------------------------------------------------
%macro  .STARTUP  0
;group dgroup .data .bss
        global   _start
_start:
%endmacro
;;-------------------------------------------------------------------


;;;-------------------------------------------------------------------------
; .EXIT
; terminate program and return 0

%macro  .EXIT  0
        mov    eax, SYS_EXIT
        xor    ebx, ebx  ;set ebx to zero as return code
        int    0x80
%endmacro

;;-------------------------------------------------------------------
%macro  .DATA 0
        segment .data
%endmacro
;;-------------------------------------------------------------------

;;-------------------------------------------------------------------
%macro  .UDATA 0
        segment .bss
%endmacro
;;-------------------------------------------------------------------

;;-------------------------------------------------------------------
%macro  .CODE 0
        segment .data
        segment .bss
        segment .text
%endmacro
;;-------------------------------------------------------------------


;;-------------------------------------------------------------------
%macro  nwln  0 
        call    proc_nwln
%endmacro
;;-------------------------------------------------------------------


;;;-------------------------------------------------------------------------
; PutCh source
; source: value / register / memory
; Displays the character located at source

%macro  PutCh  1
	;'''''''''''''''''''''''''''''''
	SECTION .bss
	%%CHAR resb 1

	;'''''''''''''''''''''''''''''''
	SECTION .text
	pusha
	mov     al, %1
	mov     [%%CHAR], al
	mov     eax, SYS_WRITE
	mov     ebx, STDOUT
	mov     ecx, %%CHAR
	mov     edx, 1  ;length of a character
	int     0x80
	popa
%endmacro

;;-------------------------------------------------------------------
%macro  PutStr  1 
        push    ECX
        mov     ECX,%1
        call    proc_PutStr
        pop     ECX
%endmacro
;;-------------------------------------------------------------------


;;-------------------------------------------------------------------
%macro  GetStr  1-2 81
        push    ESI
        push    EDI
        mov     EDI,%1
        mov     ESI,%2
        call    proc_GetStr
        pop     EDI
        pop     ESI
%endmacro
;;-------------------------------------------------------------------


;;-------------------------------------------------------------------
%macro  GetCh   1
        push    SI
        xor     SI,SI
%ifidni %1,AL
        ;inc     SI
        call    proc_GetCh
%elifidni %1,AH
        mov     SI,1
        call    proc_GetCh
%else
        push    AX
        call    proc_GetCh
        mov     %1,AL
        pop     AX
%endif
        pop     SI
%endmacro
;;-------------------------------------------------------------------


;;-------------------------------------------------------------------
%macro  PutInt  1
        push    AX
        mov     AX,%1
        call    proc_PutInt
        pop     AX
%endmacro
;;-------------------------------------------------------------------


;;-------------------------------------------------------------------
%macro  GetInt  1
%ifnidni %1,AX
        push    AX
        call    proc_GetInt
        mov     %1,AX
	  pop     AX
%else 
        call  proc_GetInt
%endif
%endmacro
;;-------------------------------------------------------------------

;;-------------------------------------------------------------------
%macro  PutLInt  1
        push    EAX
        mov     EAX,%1
        call    proc_PutLInt
        pop     EAX
%endmacro
;;-------------------------------------------------------------------

;;-------------------------------------------------------------------
%macro  GetLInt  1
%ifnidni %1,EAX
        push    EAX
        call    proc_GetLInt
        mov     %1,EAX
	  pop     EAX
%else 
        call  proc_GetLInt
%endif
%endmacro
;;-------------------------------------------------------------------

